### PR TITLE
Cleanup complete

### PR DESCRIPTION
**Pull request by ZachOhara**
All source code is confirmed to be functionally the same as the decompiled code that was released.

### CODE REVIEW

**Comment by danielgrimshaw** [comment]
Now that you've finished @ZachOhara they are going to notice all of their mistakes and fix them. Does it run yet?

# TEST ONLY IN EMULATOR FOR NOW

**Comment by danielgrimshaw** [comment]
There are typos in TODO.md (unless we have hareware as well as hardware!)

**Comment by ZachOhara** [comment]
We don't have an emulator that can model P2P wifi, so we probably won't be
able to test that. We'll have to wait until we get our harEware kit from
FTC.

**Comment by danielgrimshaw** [comment]
@ZachOhara isn't the app supposed to contain those drivers for us? Its just a normal wifi link on ssh. All phones that have wifi are capable of emulating it.

**Comment by ZachOhara** [comment]
The real problem here is getting two different emulated phones to talk to
each other; or even worse, getting an emulated phone to talk to a physical
one. The wifi link is supported natively in the Android OS, but not by the
emulator.

**Comment by danielgrimshaw** [comment]
K. But two emulators can call one another, and send data to one another through NFC (Near Field Communcation (that weird thing where you touch the backs of two phones together to send files)), so they are probably able to connect to each other through ssh, try googling it.

**Pull request merged**
